version: '3.8'

services:
  bcv-backend:
    container_name: bcv-backend
    build:
      context: ../bcv-backend
    volumes:
      - ../bcv-backend/:/bcv-backend
    ports:
      - '8080:8080'
    links:
      - db
    depends_on:
      - bcv-frontend

  bcv-frontend:
    container_name: bcv-frontend
    build:
      context: ../bcv-frontend
    volumes:
      - ../bcv-frontend/:/bcv-frontend
      - /bcv-frontend/node_modules
    ports:
      - '3000:3000'

  db:
    container_name: bcv-db
    image: mongo
    ports:
      - '27017:27017'

networks:
  blockchain-v:
